// source: pbRcsCarMessages.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck


goog.provide('proto.rcsCar.CarCommand');
goog.provide('proto.rcsCar.CarCommand.Flags');
goog.provide('proto.rcsCar.CarResponse');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rcsCar.CarCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rcsCar.CarCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rcsCar.CarCommand.displayName = 'proto.rcsCar.CarCommand';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rcsCar.CarResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rcsCar.CarResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rcsCar.CarResponse.displayName = 'proto.rcsCar.CarResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rcsCar.CarCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.rcsCar.CarCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rcsCar.CarCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rcsCar.CarCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    steering: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    gear: jspb.Message.getFieldWithDefault(msg, 2, 0),
    throttle: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    braking: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    messagetime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lastrecvmessagetime: jspb.Message.getFieldWithDefault(msg, 6, 0),
    debugstr: jspb.Message.getFieldWithDefault(msg, 7, ""),
    customstate: msg.getCustomstate_asB64(),
    packetno: jspb.Message.getFieldWithDefault(msg, 9, 0),
    flags: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rcsCar.CarCommand}
 */
proto.rcsCar.CarCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rcsCar.CarCommand;
  return proto.rcsCar.CarCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rcsCar.CarCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rcsCar.CarCommand}
 */
proto.rcsCar.CarCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSteering(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setGear(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setThrottle(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBraking(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMessagetime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastrecvmessagetime(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDebugstr(value);
      break;
    case 8:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCustomstate(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPacketno(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFixed32());
      msg.setFlags(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rcsCar.CarCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rcsCar.CarCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rcsCar.CarCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rcsCar.CarCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSteering();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getGear();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getThrottle();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getBraking();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getMessagetime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getLastrecvmessagetime();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getDebugstr();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getCustomstate_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      8,
      f
    );
  }
  f = message.getPacketno();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getFlags();
  if (f !== 0) {
    writer.writeFixed32(
      10,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.rcsCar.CarCommand.Flags = {
  NONE: 0,
  LIGHTS_LEFT: 1,
  LIGHTS_RIGHT: 2,
  SIDELIGHTS: 4,
  HEADLIGHTS: 8,
  HEADLIGHTS_FULL: 16,
  LIGHTS_FOG: 32,
  HORN: 64
};

/**
 * optional float steering = 1;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getSteering = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setSteering = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional sint32 gear = 2;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getGear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setGear = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float throttle = 3;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getThrottle = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setThrottle = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float braking = 4;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getBraking = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setBraking = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int64 messageTime = 5;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getMessagetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setMessagetime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 lastRecvMessageTime = 6;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getLastrecvmessagetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setLastrecvmessagetime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string debugStr = 7;
 * @return {string}
 */
proto.rcsCar.CarCommand.prototype.getDebugstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setDebugstr = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional bytes customState = 8;
 * @return {!(string|Uint8Array)}
 */
proto.rcsCar.CarCommand.prototype.getCustomstate = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * optional bytes customState = 8;
 * This is a type-conversion wrapper around `getCustomstate()`
 * @return {string}
 */
proto.rcsCar.CarCommand.prototype.getCustomstate_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCustomstate()));
};


/**
 * optional bytes customState = 8;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCustomstate()`
 * @return {!Uint8Array}
 */
proto.rcsCar.CarCommand.prototype.getCustomstate_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCustomstate()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setCustomstate = function(value) {
  return jspb.Message.setProto3BytesField(this, 8, value);
};


/**
 * optional int32 packetNo = 9;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getPacketno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setPacketno = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional fixed32 flags = 10;
 * @return {number}
 */
proto.rcsCar.CarCommand.prototype.getFlags = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarCommand} returns this
 */
proto.rcsCar.CarCommand.prototype.setFlags = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rcsCar.CarResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.rcsCar.CarResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rcsCar.CarResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rcsCar.CarResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    steering: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    gear: jspb.Message.getFieldWithDefault(msg, 2, 0),
    throttle: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    braking: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    messagetime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    lastrecvmessagetime: jspb.Message.getFieldWithDefault(msg, 6, 0),
    batvoltageMv: jspb.Message.getFieldWithDefault(msg, 7, 0),
    steeringadc: jspb.Message.getFieldWithDefault(msg, 8, 0),
    cartimestamp: jspb.Message.getFieldWithDefault(msg, 9, 0),
    debugrespstr: jspb.Message.getFieldWithDefault(msg, 10, ""),
    customresponse: msg.getCustomresponse_asB64(),
    responsedelay: jspb.Message.getFieldWithDefault(msg, 12, 0),
    lastrecvpacketno: jspb.Message.getFieldWithDefault(msg, 13, 0),
    speed: jspb.Message.getFloatingPointFieldWithDefault(msg, 14, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rcsCar.CarResponse}
 */
proto.rcsCar.CarResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rcsCar.CarResponse;
  return proto.rcsCar.CarResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rcsCar.CarResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rcsCar.CarResponse}
 */
proto.rcsCar.CarResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSteering(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint32());
      msg.setGear(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setThrottle(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBraking(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMessagetime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLastrecvmessagetime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBatvoltageMv(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSteeringadc(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCartimestamp(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDebugrespstr(value);
      break;
    case 11:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setCustomresponse(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setResponsedelay(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLastrecvpacketno(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSpeed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rcsCar.CarResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rcsCar.CarResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rcsCar.CarResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rcsCar.CarResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSteering();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
  f = message.getGear();
  if (f !== 0) {
    writer.writeSint32(
      2,
      f
    );
  }
  f = message.getThrottle();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getBraking();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getMessagetime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getLastrecvmessagetime();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getBatvoltageMv();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getSteeringadc();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getCartimestamp();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getDebugrespstr();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getCustomresponse_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      11,
      f
    );
  }
  f = message.getResponsedelay();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getLastrecvpacketno();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getSpeed();
  if (f !== 0.0) {
    writer.writeFloat(
      14,
      f
    );
  }
};


/**
 * optional float steering = 1;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getSteering = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setSteering = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional sint32 gear = 2;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getGear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setGear = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional float throttle = 3;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getThrottle = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setThrottle = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float braking = 4;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getBraking = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setBraking = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int64 messageTime = 5;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getMessagetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setMessagetime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 lastRecvMessageTime = 6;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getLastrecvmessagetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setLastrecvmessagetime = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 batVoltage_mV = 7;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getBatvoltageMv = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setBatvoltageMv = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 steeringAdc = 8;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getSteeringadc = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setSteeringadc = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 carTimestamp = 9;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getCartimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setCartimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string debugRespStr = 10;
 * @return {string}
 */
proto.rcsCar.CarResponse.prototype.getDebugrespstr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setDebugrespstr = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional bytes customResponse = 11;
 * @return {!(string|Uint8Array)}
 */
proto.rcsCar.CarResponse.prototype.getCustomresponse = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * optional bytes customResponse = 11;
 * This is a type-conversion wrapper around `getCustomresponse()`
 * @return {string}
 */
proto.rcsCar.CarResponse.prototype.getCustomresponse_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getCustomresponse()));
};


/**
 * optional bytes customResponse = 11;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getCustomresponse()`
 * @return {!Uint8Array}
 */
proto.rcsCar.CarResponse.prototype.getCustomresponse_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getCustomresponse()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setCustomresponse = function(value) {
  return jspb.Message.setProto3BytesField(this, 11, value);
};


/**
 * optional int32 responseDelay = 12;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getResponsedelay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setResponsedelay = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 lastRecvPacketNo = 13;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getLastrecvpacketno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setLastrecvpacketno = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional float speed = 14;
 * @return {number}
 */
proto.rcsCar.CarResponse.prototype.getSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 14, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rcsCar.CarResponse} returns this
 */
proto.rcsCar.CarResponse.prototype.setSpeed = function(value) {
  return jspb.Message.setProto3FloatField(this, 14, value);
};


